[2024-08-14T23:09:56.063+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T23:09:56.135+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_etl_pipeline.upload_data_to_s3 manual__2024-08-14T23:09:49.741762+00:00 [queued]>
[2024-08-14T23:09:56.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_etl_pipeline.upload_data_to_s3 manual__2024-08-14T23:09:49.741762+00:00 [queued]>
[2024-08-14T23:09:56.147+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T23:09:56.163+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_data_to_s3> on 2024-08-14 23:09:49.741762+00:00
[2024-08-14T23:09:56.171+0000] {standard_task_runner.py:64} INFO - Started process 53 to run task
[2024-08-14T23:09:56.174+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_etl_pipeline', 'upload_data_to_s3', 'manual__2024-08-14T23:09:49.741762+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/rdt_dags.py', '--cfg-path', '/tmp/tmpbf83iyy4']
[2024-08-14T23:09:56.176+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask upload_data_to_s3
[2024-08-14T23:09:56.235+0000] {task_command.py:426} INFO - Running <TaskInstance: reddit_etl_pipeline.upload_data_to_s3 manual__2024-08-14T23:09:49.741762+00:00 [running]> on host 6507decc16dc
[2024-08-14T23:09:56.321+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ROmin Katre' AIRFLOW_CTX_DAG_ID='reddit_etl_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T23:09:49.741762+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T23:09:49.741762+00:00'
[2024-08-14T23:09:56.323+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T23:09:56.335+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T23:09:56.336+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/s3_data_pipeline.py", line 5, in uplaod_s3_pipeline
    file_path = ti.xcomm_pull(task_ids = 'reddit_data_extraction', key = 'return_value')
AttributeError: 'TaskInstance' object has no attribute 'xcomm_pull'
[2024-08-14T23:09:56.351+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=reddit_etl_pipeline, task_id=upload_data_to_s3, run_id=manual__2024-08-14T23:09:49.741762+00:00, execution_date=20240814T230949, start_date=20240814T230956, end_date=20240814T230956
[2024-08-14T23:09:56.366+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task upload_data_to_s3 ('TaskInstance' object has no attribute 'xcomm_pull'; 53)
[2024-08-14T23:09:56.387+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-14T23:09:56.406+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T23:09:56.409+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
